remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: UniAuto MCP Server
description: Universal Test Automation MCP Server with self-healing capabilities and AI integration

show_downloads: true

navbar:
  - title: Home
    url: /
  - title: Smithery.ai Integration
    url: /smithery/
  - title: GitHub
    url: https://github.com/samuelvinay91/uniauto-mcp-server
  - title: API Reference
    url: /api/
  - title: Smithery.ai Setup
    url: /smithery-setup/
  - title: Self-healing
    url: /self-healing/
  - title: AI Integration
    url: /ai-integration/

social:
  - title: GitHub
    url: https://github.com/samuelvinay91/uniauto-mcp-server
    icon: github
  - title: Twitter
    url: https://twitter.com/uniauto
    icon: twitter

footer:
  links:
    - title: GitHub
      url: https://github.com/samuelvinay91/uniauto-mcp-server
    - title: Issues
      url: https://github.com/samuelvinay91/uniauto-mcp-server/issues
    - title: License
      url: https://github.com/samuelvinay91/uniauto-mcp-server/blob/main/LICENSE